export enum NavBarAction {
  ENTER_ADD_MODE = 'ENTER_ADD_MODE',
  ENTER_SEARCH_MODE = 'ENTER_SEARCH_MODE',
  EXIT_ADD_MODE = 'EXIT_ADD_MODE',
  EXIT_SEARCH_MODE = 'EXIT_SEARCH_MODE',
  TO_INBOX = 'TO_INBOX',
  TO_TODAY = 'TO_TODAY',
  TO_UPCOMING = 'TO_UPCOMING',
  FILTER_AND_LABELS = 'FILTER_AND_LABELS',
}
