name: Autolink Jira Tickets

on:
  pull_request:
    types: [opened, edited]

jobs:
  autolink-jira-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Parse Jira Tickets
        run: |
          # Example script to parse Jira tickets from PR title and update description
          PR_TITLE=$(jq -r .pull_request.title $GITHUB_EVENT_PATH)
          JIRA_TICKETS=$(echo $PR_TITLE | grep -o '[A-Z][A-Z0-9]*-[0-9]\+')
          DESCRIPTION="### Jira Tickets\n"
          
          for ticket in $JIRA_TICKETS; do
            DESCRIPTION+="[JIRA-$ticket](https://ankush2001garg.atlassian.net/browse/JIRA-$ticket)\n"
          done

          echo "::set-output name=description::$DESCRIPTION"

      - name: Update Pull Request Description
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const description = `$(echo $DESCRIPTION)`;
            github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: description
            });
